name: mtbreaker
channels:
  - pytorch
  - nvidia
  - xformers
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch-cuda=12.1
  - pytorch
  - cudatoolkit
  - xformers
  - pip
  - pip:
      - unsloth
      - "trl>=0.19.0,<0.25.0" 
      - peft
      - accelerate
      - bitsandbytes
      
      - unbabel-comet
      - sacrebleu
      - sentence-transformers
      - langdetect
      
      - wandb
      - pandas
      - seaborn
      - rich
      
      - datasets
      - transformers

      - -e git+https://github.com/prosho-97/guardians-mt-eval.git#egg=sentinel_metric